version: "3"

services:
  backend:
    env_file:
      - .env # This should be in the same folder where you run docker-compose
    image: lephenix47/dev-portfolio-bun-hono-backend-dev:latest # Use the pre-built image
    ports:
      - "3000:3000"
    restart: always # Ensures the container restarts if it crashes
