version: "3"

services:
  backend:
    env_file:
      - ../.env # Path to the .env file in the root directory
    build:
      context: ../ # Pointing to the root of the project (because that's where your app's context should be)
      dockerfile: ./Docker/Dockerfile # Path to Dockerfile inside the Docker/ folder
    image: lephenix47/dev-portfolio-bun-hono-backend-dev:latest # Name of our image
    ports:
      - "3000:3000"
