name: Test

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Check environment and secrets
        run: |
          echo "The current environment is: ${{ vars.PORT }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2 # See https://github.com/marketplace/actions/setup-bun
        with:
          bun-version: "1.2.2"

      - name: Install dependencies
        run: bun install --save-text-lockfile

      - name: Cache Bun Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('package.json', 'bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Create .env file from sample and secrets
        run:
          | # Copy .env_sample to .env and clean up optional variables after # Facultative, then update mandatory variables
          sed '/# Facultative/,$d' .env_sample > .env

          sed -i "s|^NODE_ENV=.*|NODE_ENV=${{ vars.NODE_ENV }}|" .env
          sed -i "s|^DISCORD_WEBHOOK_URL=.*|DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}|" .env

      - name: Check .env file contents
        run: cat .env

      - name: Run tests
        run: bun run test

      - name: Build the project
        run: bun run app:build

  docker:
    needs: build # This ensures Docker build runs only if tests pass
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
