name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Check environment and secrets
        run: |
          echo "The current environment is: ${{ github.environment }}"

          # Now echo the relevant secrets based on the environment set
          echo "Secrets for environment ${GITHUB_ENV}:"
          echo "NODE_ENV=${{ secrets.NODE_ENV }}"
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}"

          if [[ "${{ github.environment }}" == "production" ]]; then
            echo "Using production secrets"
          elif [[ "${{ github.environment }}" == "development" ]]; then
            echo "Using development secrets"
          elif [[ "${{ github.environment }}" == "staging" ]]; then
            echo "Using staging secrets"
          else
            echo "Using default secrets"
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2 # See https://github.com/marketplace/actions/setup-bun
        with:
          bun-version: "1.2.2"

      - name: Install dependencies
        run: bun install --save-text-lockfile

      - name: Create .env file from sample and secrets
        run: |
          # Copy .env_sample to .env and clean up optional variables after # Facultative
          sed '/# Facultative/,$d' .env_sample > .env

          # Update mandatory and critical variables in .env
          sed -i "s|^NODE_ENV=.*|NODE_ENV=${{ secrets.NODE_ENV }}|" .env
          sed -i "s|^DISCORD_WEBHOOK_URL=.*|DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}|" .env

      - name: Check .env file contents
        run: cat .env

      - name: Cache Bun Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Run tests
        run: bun test

      - name: Build the project
        run: bun run build
