name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2 # See https://github.com/marketplace/actions/setup-bun
        with:
          bun-version: "1.2.2"

      - name: Install dependencies
        run: bun install --save-text-lockfile

      - name: Create .env file from sample and secrets
        run: |
          # Copy .env_sample to .env
          cp .env_sample .env 

          # Update mandatory and critical variables in .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env

      - name: Cache Bun Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Run tests
        run: bun test

      - name: Build the project
        run: bun run build
