name: Deploy to VPS

on:
  workflow_call: # This allows it to be triggered from another workflow
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.VPS_HOSTNAME }}
          username: ${{ vars.VPS_USERNAME }}
          password: ${{ secrets.VPS_DEPLOYER_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "✅ SSH connection successful"
            whoami
            hostname
            uptime
